# Generated by Django 3.0.6 on 2020-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeunlike',
            name='like',
            field=models.CharField(choices=[('like', 'Like'), ('unlike', 'Unlike')], default='unlike', max_length=6),
        ),
    ]
