# Generated by Django 3.0.6 on 2020-05-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20200528_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeunlike',
            options={'verbose_name': 'Like/Unlike', 'verbose_name_plural': 'Likes/Unlikes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
