# Generated by Django 3.0.6 on 2020-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_auto_20200530_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeunlike',
            name='like',
            field=models.BooleanField(verbose_name='Like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
