# Generated by Django 3.0.6 on 2020-05-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_auto_20200530_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeunlike',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
